[package]
name = "EconRust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand= '0.9.0-alpha.2'
log = "0.4.22"
env_logger = "0.11.3"
chrono = "0.4.38"
fern = "0.6.2"
rand_distr = "0.5.0-alpha.3"
csv = "1.3.0"